apiVersion: 1

datasources:
  # configruation setup viewable here: https://github.com/grafana/mqtt-datasource/blob/main/src/ConfigEditor.tsx
  - name: MQTT
    type: grafana-mqtt-datasource
    editable: true
    isDefault: true
    secureJsonData:
      password: ${MQTT_PASSWORD}
    jsonData:
      username: ${MQTT_USERNAME}
      uri: host.docker.internal:1883
  
  - name: WebSocket API
    type: golioth-websocket-datasource
    editable: true
    isDefault: false
    jsonData: 
      host: ws://host.docker.internal:3001/grafana-ws

  # - name: Postgres
  #   type: postgres
  #   url: postgres:5432
  #   user: yourusername
  #   secureJsonData:
  #     password: "yourpassword"
  #   jsonData:
  #     database: mqtt
  #     sslmode: "disable" # disable/require/verify-ca/verify-full
